import { Inject, Injectable } from '@nestjs/common';
import { MASTRA } from '../config/mastra.constants';
import { Mastra } from '@mastra/core/mastra';
import { QuestEngineService } from 'src/modules/quest-engine/application/service/quest-engine.service';
import { RESPONSE_SERVICE } from 'src/common/response_service/interface/response.interface';
import { ResponseService } from 'src/common/response_service/service/response.service';
import { PromptInjectionDetector } from '@mastra/core/processors';
import { GEMINI_CLIENT } from '../config/model.config';
import { GoogleGenerativeAIProvider } from '@ai-sdk/google';
import { MastraLanguageModel } from '@mastra/core';
import { CreateChatDto } from '../dto/create-chat.dto';

@Injectable()
export class MastraService {
  private readonly mastra: Mastra;
  private readonly model: MastraLanguageModel;

  constructor(
    @Inject(MASTRA)
    mastraProvider: Mastra,
    private readonly questEngine: QuestEngineService,
    @Inject(RESPONSE_SERVICE)
    private readonly responseService: ResponseService,
    @Inject(GEMINI_CLIENT)
    geminiClient: GoogleGenerativeAIProvider,
  ) {
    this.responseService.setContext(MastraService.name);
    this.mastra = mastraProvider;
    this.model = geminiClient('gemini-2.0-flash');
  }

  public async chatWithAgent(dto: CreateChatDto) {
    try {
      const { message, history } = dto;

      const questResp = await this.questEngine.getQuest(message);

      if (questResp?.payload?.answer) {
        return this.responseService.createResponse({
          type: 'OK',
          message: 'Answer pre-generated',
          payload: { answer: questResp?.payload?.answer ?? '' },
        });
      }

      const allowedQuestions = (await this.questEngine.getAllQuests()).payload;

      const assistantPrompt = `Allowed questions and answers:\n${allowedQuestions
        .map(
          (s) =>
            `- Q: ${s.question ?? JSON.stringify(s)}\n  A: ${s.answer ?? ''}`,
        )
        .join('\n')}`;

      const stream = await this.mastra
        .getAgent('questAgent')
        .generateVNext([{ role: 'user', content: dto.message }], {
          format: 'aisdk',
          context: [
            { role: 'assistant', content: assistantPrompt },
            ...(Array.isArray(history) ? history : []),
          ],
          inputProcessors: [
            new PromptInjectionDetector({
              model: this.model,
              strategy: 'rewrite',
            }),
          ],
          providerOptions: {
            google: {
              safetySettings: [
                {
                  category: 'HARM_CATEGORY_UNSPECIFIED',
                  threshold: 'BLOCK_LOW_AND_ABOVE',
                },
                {
                  category: 'HARM_CATEGORY_HATE_SPEECH',
                  threshold: 'BLOCK_LOW_AND_ABOVE',
                },
                {
                  category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
                  threshold: 'BLOCK_LOW_AND_ABOVE',
                },
                {
                  category: 'HARM_CATEGORY_HARASSMENT',
                  threshold: 'BLOCK_LOW_AND_ABOVE',
                },
                {
                  category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
                  threshold: 'BLOCK_LOW_AND_ABOVE',
                },
              ],
              thinkingConfig: {
                thinkingBudget: 8192,
                includeThoughts: true,
              },
            },
          },
        });

      return this.responseService.createResponse({
        message: 'Answer generated by agent (fallback)',
        type: 'OK',
        payload: {
          answer: stream.text,
        },
      });
    } catch (error) {
      return this.responseService.errorHandler({ error });
    }
  }
}
